services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gracker
    env_file:
      - .env.dev
    depends_on:
      - database
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    restart: always

  database:
    image: mysql:latest
    container_name: gracker-database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # MySQL은 기본적으로 root 패스워드를 설정해야 함
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - gracker-database:/var/lib/mysql

volumes:
  gracker-database: